########  SAC  #######

device: 'cuda'

# Env
env_name: 'maze2d-open-v1'
image_size: 128
distractor_num: 10
bounds: [-0.7, 0.7, -0.7, 0.7]
goal_num: 4

# Misc
seed: 123
work_dir: '.'
log_path: './logs/'
model_path: 'pretrained/'

# Model
noise_steps: 400

# Train
epsilon: 0.00002
train_lr: 0.0002
epochs: 1500
batch_size: 16

# Eval
eval_batch_size: 10
eval_init_state: [0., 0.]