########  SAC  #######

device: 'cuda'

# Env
env_name: 'maze2d-open-v1'
image_size: 128
bounds: [-0.7, 0.7, -0.7, 0.7]


# Misc
seed: 123
work_dir: '.'
log_path: './logs/'
model_path: 'pretrained/'

# Model
noise_steps: 300

# Train
epsilon: 0.00002
train_lr: 0.0002
epochs: 4000
batch_size: 18

# Eval
eval_batch_size: 10
eval_init_state: [0.5, 0.5]