########  SAC  #######

device: 'cuda'

# Env
env_name: 'maze2d-open-v1'
image_size: 128
distractor_num: 10
goal_bounds: [-0.8, 0.8, -0.8, 0.8]
agent_bounds: [-1.,1.,-1.,1.]
goal_num: 3

# Misc
seed: 123
work_dir: '.'
log_path: './logs/'
model_path: 'pretrained/'

# Model
noise_steps: 500
beta_start: 0.00001
beta_end: 0.005

# Train
train_lr: 0.0001
epochs: 50000
batch_size: 24

# Eval
eval_samples: 1000
