########  SAC  #######

device: 'cuda'

# Env
env_name: 'maze2d-open-v1'
image_size: 128
distractor_num: 10

# Misc
seed: 123
work_dir: '.'
log_path: './logs/'
model_path: 'pretrained/'

# Model
noise_steps: 300

# Train
epsilon: 0.00002
train_lr: 0.0002
epochs: 3000
batch_size: 24

# Eval
eval_batch_size: 20
init_state: [4, 4]