device: 'cuda'

# Env
image_size: 128
goal_bounds: [-0.8, 0.8, -0.8, 0.8]
agent_bounds: [-1.,1.,-1.,1.]
obstacles: [[80,80,180,160]]  # O : [70, 80, 180, 160]

# Misc
seed: 123
work_dir: '.'
log_path: './logs/'
model_path: 'pretrained/'

# Diffusion & Model
u0: 100  # 100
min_heat_step: 1568     # should be 2 * n**2
max_heat_step: 72200    # should be 2 * n**2
noise_steps: 10 # 200
sample_num: 10   # 1000
time_type: 'exp'

# Train
epochs: 1
train_lr: 0.0001
iterations: 8000
random_goals: 1
batch_size: 24


# Eval
