device: 'cuda'

# Env
image_size: 128
goal_bounds: [-0.8, 0.8, -0.8, 0.8]
agent_bounds: [-1.,1.,-1.,1.]
goal_num: 1
obstacles: [[0,80,180,160]]  # O : [70, 80, 180, 160]

# Misc
seed: 123
work_dir: '.'
log_path: './logs/'
model_path: 'pretrained/'

# Diffusion & Model
u0: 100
heat_steps: 5000 # 50000
noise_steps: 200 # 200
precision: 'single'

# Train
epochs: 15
train_lr: 0.0001
iterations: 1500
batch_size: 24

# Eval
eval_samples: 1000
