# SAC
env_name: 'maze2d-open-v0'
eval: True # Evaluates a policy every 10 episode
gamma: 0.99
tau: 0.005
critic_lr: 0.0003
actor_lr: 0.0003
alpha: 0.2
automatic_entropy_tuning: False
seed: 123456
batch_size: 256
num_steps: 1000001
hidden_size: 256
updates_per_step: 1
start_steps: 10000
target_update_interval: 1
replay_size: 1000000
cuda: store_true
