########  SAC  #######

# Env
env_name: 'maze2d-open-v1'
image_size: 64
target_point: [1.0, 1.0]
distractor_num: 10

# Replay Buffer
replay_buffer_capacity: 100000

# Train
init_steps: 1000
num_train_steps: 1000000
batch_size: 32
hidden_dim: 1024

# Eval
eval_freq: 1000
num_eval_episodes: 10

# Critic 
critic_lr: 0.001
critic_beta: 0.9
critic_tau: 0.01
critic_target_update_freq: 2

# Actor
actor_lr: 0.001
actor_beta: 0.9
actor_log_std_min: -10
actor_log_std_max: 2
actor_update_freq: 2

# Encoder
feature_dim: 128
encoder_lr: 0.001
encoder_tau: 0.05

# SAC
discount: 0.99
init_temperature: 0.1
alpha_lr: 0.0001
alpha_beta: 0.5

# Misc
seed: 123
work_dir: '.'
save_tb: False
save_video: False
save_model: False
detach_encoder: False

log_path: './logs/'
log_interval: 100

model_path: 'pretrained/'
